Pream
esc-chula/larngearcamp-frontend pull request #72
Opened 2022-09-02 11:30 UTC by preamza02

ทำตาม https://docs.google.com/document/d/1HLeDNsQpmkt7CEcFS9kdMgCxUQFsOB_N4vmu-Lu20PE/edit
แก้ logo หน้า Login
ตั้งเวลาเปลี่ยน text end fake date 30 ก.ย.

2022-09-02 11:57 UTC, Nitiwat-owen requested changes
Could you make the text be center or reduce the height of the background picture.
![image](https://user-images.githubusercontent.com/77772598/188137943-6c028216-9eac-4721-8e85-f89b9a5aa2f0.png)

2022-09-02 11:57 UTC, Nitiwat-owen commented on src/core/constants/timeline.constant.tsx
>    },
Unfortunately, the interview day has changed to 30 October 2022.

2022-09-02 12:01 UTC, Nitiwat-owen requested changes
Reduce the gap between Facebook and Instagram embedded
<img width="400" alt="Screen Shot 2565-09-02 at 18 59 49" src="https://user-images.githubusercontent.com/77772598/188138594-3066d4d4-53bf-4929-ada7-c6a876b4d3ac.png">

2022-09-02 12:03 UTC, Nitiwat-owen requested changes
Could you style the text be inline.
<img width="371" alt="Screen Shot 2565-09-02 at 19 02 46" src="https://user-images.githubusercontent.com/77772598/188138924-8b9637e0-3365-4722-bca4-534aefdc66b5.png">

2022-09-02 12:10 UTC, Nitiwat-owen requested changes
As you can see that there are some errors because of missing the key property of the mapping component, so I would you to add the key props in that missing component.
<img width="519" alt="Screen Shot 2565-09-02 at 19 09 14" src="https://user-images.githubusercontent.com/77772598/188139853-fdb7ce3b-3739-46bc-80ae-3df1e60d08bf.png">

2022-09-02 15:40 UTC, preamza02 commented
new commit : 
fix from commend
fix logo size in sidebar
fix gap below Instagram embed

2022-09-02 15:43 UTC, preamza02 commented
> Reduce the gap between Facebook and Instagram embedded <img alt="Screen Shot 2565-09-02 at 18 59 49" width="400" src="https://user-images.githubusercontent.com/77772598/188138594-3066d4d4-53bf-4929-ada7-c6a876b4d3ac.png">

i reduce the gap from 6 px to 4 px  
![image](https://user-images.githubusercontent.com/79450371/188190252-114828dc-87e1-4e37-b38b-ffb909ec9ab0.png)

2022-09-02 15:44 UTC, Nitiwat-owen requested changes

2022-09-02 15:44 UTC, Nitiwat-owen commented on src/core/providers/announce.provider.tsx
>    },
We will let the student apply the form at 6pm, so please edit the time openning.

2022-09-02 15:44 UTC, Nitiwat-owen commented on src/core/constants/timeline.constant.tsx
>    }
Also, the camp has changed to 5 - 8 Jan 23. I think you have to change the vaccine qualification too.  Please change that the applicant must get the vaccine before 22 Dec 2022.

2022-09-03 05:11 UTC, Nitiwat-owen requested changes

2022-09-03 05:11 UTC, Nitiwat-owen commented on src/core/constants/contact.constant.tsx
>  ]
Boards want to change the contact information to be id line.
พี่ตีตี้  line id : tity1506
พี่บุ๊ค  line id : book11653
พี่เจิ้ง  line id : pasana_jerng
พี่เฟรน line id : friendlypp
which I think you have to change the icon also.

2022-09-03 09:21 UTC, preamza02 commented on src/core/constants/contact.constant.tsx
>  ]
i have changed it

2022-09-03 09:33 UTC, Nitiwat-owen requested changes
Could you please decrease the size of file bg6.jpg to be as same as the others (width : 1567px, height : 1045px).

2022-09-04 10:15 UTC, preamza02 commented
> 

hi i have changed it

2022-09-04 10:29 UTC, Nitiwat-owen approved these changes

2022-09-04 10:30 UTC, merged