Update home page's title, description, and qualification
esc-chula/larngearcamp-frontend pull request #9
Opened 2021-11-05 14:57 UTC by PKhing

2021-11-05 15:26 UTC, saenyakorn requested changes

2021-11-05 15:26 UTC, saenyakorn commented on src/modules/home/home-description-image.module.tsx
> +      </div>
ฝากกำหนด width, height ด้วยนะ ไม่งั้นมันจะเกิด [Cumulative layout shift](https://web.dev/cls/) ส่งผลต่อ SEO ได้ + ใส่ alt ด้วยมีผลต่อ SEO เหมือนกัน

2021-11-05 15:26 UTC, saenyakorn commented on src/modules/home/home-description-image.module.tsx
> +        <img
Behaviour ตอนนี้คือแม้ว่าจะวนรูปครบ 7 รูปแล้ว แต่พอกลับมารูปแรกมันก็ยัง fetch ใหม่เหมือนเดิม ฝากแก้ตรงนี้หน่อยนะ
<img width="191" alt="Screen Shot 2564-11-05 at 22 18 38" src="https://user-images.githubusercontent.com/33742791/140534542-b5d39481-0d4e-4ce3-95ca-755a271f4051.png">

Note: อาจจะเป็นโหลดรูปหรือสองรูปแรกจากก่อน hydrate แล้วหลังจาก hydrate ค่อย ๆ ทยอย fetch รูปใน background

2021-11-05 15:26 UTC, saenyakorn commented on src/modules/home/home-description-image.module.tsx
> +        <img
ถ้าทำเป็นอย่างงี้ด้วยจะดีมาก https://v4.mui.com/components/skeleton/#inferring-dimensions

2021-11-07 15:35 UTC, saenyakorn reviewed
For some reason 
https://user-images.githubusercontent.com/33742791/140651559-e3cd2964-fb4c-449e-854f-b8ccd34933cd.mov

2021-11-07 15:35 UTC, saenyakorn commented on src/modules/home/home-description-image.module.tsx
> +        })}
```suggestion
        {descriptionConstant.map(({ src }, idx) => (
            <img
              src={src}
              key={`home-image-${idx}`}
              alt="home-image-${idx}"
              onLoad={() => idx===0 && setLoading(false)}
              style={{ display: index === idx && !isLoading ? "block" : "none" }}
              className={classes.image}
            />
          )
        )}
```

2021-11-07 15:56 UTC, PKhing commented
> For some reason
> 
>  140651559-e3cd2964-fb4c-449e-854f-b8ccd34933cd.mov

![image](https://user-images.githubusercontent.com/19553305/140652225-64d895de-6192-403a-8bef-74b6ccd201a5.png)
It's because Timeline component 😢

2021-11-07 15:58 UTC, saenyakorn approved these changes

2021-11-07 16:00 UTC, merged